#!/usr/bin/env python3
"""Lean/Mathlib configuration — path discovery, validation, and serialization.

Provides the single source of truth for the Lean toolchain and Mathlib cache
used by T2 compilation.  Paths flow through this module rather than being
hardcoded in ``t2_real.py`` (the historical approach).

Loading chain (later overrides earlier):
    1. ``LeanConfig`` defaults (hardcoded fallbacks)
    2. Auto-discovery from filesystem (``discover_lean()``)
    3. ``omega.toml [lean]`` section (generated by ``omega init``)

Usage
-----
    >>> from omega.resource.lean_config import load_lean_config, LeanConfig
    >>> cfg = load_lean_config()
    >>> cfg.project_path
    PosixPath('<project-dir>')
    >>> cfg.lean_bin
    PosixPath(os.path.expanduser('~/.elan/toolchains/4.30.0/bin/lean'))

To regenerate after a Lean upgrade::

    omega init --force
"""

from __future__ import annotations

import os
import subprocess
import tomllib
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

# ── Default paths (fallbacks when nothing else works) ──────────

_DEFAULT_PROJECT = Path.home() / "lean-paper-plane"
_DEFAULT_LEAN_VERSION = "4.30.0"
_DEFAULT_TOOLCHAIN = Path.home() / ".elan" / "toolchains" / _DEFAULT_LEAN_VERSION


# ── LeanConfig dataclass ────────────────────────────────────────


@dataclass
class LeanConfig:
    """Pinned Lean/Mathlib toolchain configuration.

    Fields
    ------
    version : str
        Lean version from ``lean-toolchain`` (e.g. ``"4.30.0"``).
    project_path : Path
        Absolute path to the Lean project that has Mathlib cached.
    lean_bin : Path
        Absolute path to the ``lean`` binary matching *version*.
    lake_bin : Path
        Absolute path to the ``lake`` binary.
    olean_count : int
        Number of ``.olean`` files in the Mathlib cache (health indicator).
    mathlib_size_gb : float
        On-disk size of the Mathlib cache in GB.
    compile_channel : str
        Primary compile channel: ``"lake_env"`` or ``"bare_lean"``.
    compile_fallback : list[str]
        Ordered fallback channels if the primary fails.
    _source : str
        Where this config was loaded from (``""`` = defaults only).
    """

    version: str = _DEFAULT_LEAN_VERSION
    project_path: Path = _DEFAULT_PROJECT
    lean_bin: Path = _DEFAULT_TOOLCHAIN / "bin" / "lean"
    lake_bin: Path = _DEFAULT_TOOLCHAIN / "bin" / "lake"
    olean_count: int = 0
    mathlib_size_gb: float = 0.0
    compile_channel: str = "lake_env"
    compile_fallback: list[str] = field(default_factory=lambda: ["bare_lean"])
    _source: str = ""

    # ── Helpers ──

    def project_exists(self) -> bool:
        """Check if the Lean project directory exists."""
        return self.project_path.is_dir()

    def binaries_ok(self) -> bool:
        """Check if both lean and lake binaries exist."""
        return self.lean_bin.is_file() and self.lake_bin.is_file()

    def mathlib_ok(self) -> bool:
        """Check if Mathlib oleans exist."""
        if not self.project_exists():
            return False
        return self.olean_count > 0

    def summary(self) -> str:
        """Human-readable one-liner."""
        return (
            f"Lean {self.version} | "
            f"{'✅' if self.binaries_ok() else '❌'} binaries | "
            f"{'✅' if self.mathlib_ok() else '❌'} mathlib "
            f"({self.olean_count} oleans, {self.mathlib_size_gb:.1f} GB) | "
            f"channel={self.compile_channel}"
        )

    def to_dict(self) -> dict[str, Any]:
        """Export to a plain JSON-safe dict."""
        return {
            "version": self.version,
            "project_path": str(self.project_path),
            "binary": {
                "lean": str(self.lean_bin),
                "lake": str(self.lake_bin),
            },
            "mathlib": {
                "olean_count": self.olean_count,
                "size_gb": self.mathlib_size_gb,
            },
            "compile": {
                "channel": self.compile_channel,
                "fallback": list(self.compile_fallback),
            },
        }

    @classmethod
    def from_dict(cls, d: dict[str, Any], source: str = "") -> LeanConfig:
        """Create from a nested dict (e.g., parsed TOML [lean] section)."""
        kwargs: dict[str, Any] = {"_source": source}
        kwargs["version"] = str(d.get("version", _DEFAULT_LEAN_VERSION))

        raw_project = d.get("project_path", "")
        if raw_project:
            kwargs["project_path"] = Path(raw_project)

        binary = d.get("binary", {})
        if isinstance(binary, dict):
            if "lean" in binary:
                kwargs["lean_bin"] = Path(str(binary["lean"]))
            if "lake" in binary:
                kwargs["lake_bin"] = Path(str(binary["lake"]))

        mathlib = d.get("mathlib", {})
        if isinstance(mathlib, dict):
            kwargs["olean_count"] = int(mathlib.get("olean_count", 0))
            kwargs["mathlib_size_gb"] = float(mathlib.get("size_gb", 0.0))

        compile_ = d.get("compile", {})
        if isinstance(compile_, dict):
            if "channel" in compile_:
                kwargs["compile_channel"] = str(compile_["channel"])
            if "fallback" in compile_:
                kwargs["compile_fallback"] = list(compile_["fallback"])

        return cls(**kwargs)

    def to_toml_section(self) -> str:
        """Return the ``[lean]`` TOML section as a string."""
        lines: list[str] = []
        lines.append("# ── Lean/Mathlib Toolchain ──────────────────────────────")
        lines.append("# Auto-detected by ``omega init``.  Regenerate with:")
        lines.append("#   omega init --force")
        lines.append("")
        lines.append("[lean]")
        lines.append(f'version = "{self.version}"')
        lines.append('# Absolute path to Lean project with Mathlib cache')
        lines.append(f'project_path = "{self.project_path}"')
        lines.append("")
        lines.append("[lean.binary]")
        lines.append(f'lean = "{self.lean_bin}"')
        lines.append(f'lake = "{self.lake_bin}"')
        lines.append("")
        lines.append("[lean.mathlib]")
        lines.append(f"olean_count = {self.olean_count}")
        lines.append(f"size_gb = {self.mathlib_size_gb:.1f}")
        lines.append("")
        lines.append("[lean.compile]")
        lines.append(f'channel = "{self.compile_channel}"')
        lines.append(f"fallback = {self.compile_fallback!r}")
        lines.append("")
        return "\n".join(lines)


# ── Config file helpers ─────────────────────────────────────────


def _find_config_file() -> str:
    """Search for an Omega config file (reuses same logic as config.py).

    Order: 1) OMEGA_CONFIG env var
           2) CWD/omega.toml
           3) CWD/.omega/config.toml
           4) ~/.omega/config.toml
    Returns empty string if none found.
    """
    env_path = os.environ.get("OMEGA_CONFIG", "")
    if env_path and Path(env_path).is_file():
        return env_path

    candidates = [
        Path.cwd() / "omega.toml",
        Path.cwd() / ".omega" / "config.toml",
        Path.home() / ".omega" / "config.toml",
    ]
    for p in candidates:
        if p.is_file():
            return str(p)
    return ""


def _read_lean_from_toml(path: str) -> dict[str, Any] | None:
    """Read the ``[lean]`` section from a TOML file.

    Returns None if the file doesn't exist or has no [lean] section.
    """
    try:
        raw = Path(path).read_text(encoding="utf-8")
        data = tomllib.loads(raw)
        return data.get("lean")
    except (FileNotFoundError, tomllib.TOMLDecodeError):
        return None


# ── Auto-discovery ──────────────────────────────────────────────


def _read_lean_toolchain(project_dir: Path) -> str:
    """Read the Lean version from a project's ``lean-toolchain`` file.

    Returns ``_DEFAULT_LEAN_VERSION`` if the file is missing or unreadable.

    Strips the ``v`` prefix from versions like ``v4.30.0`` -> ``4.30.0``
    to match elan's toolchain directory naming (which omits the ``v``).
    """
    toolchain_file = project_dir / "lean-toolchain"
    if not toolchain_file.is_file():
        return _DEFAULT_LEAN_VERSION
    try:
        raw = toolchain_file.read_text().strip()
        # Format: "leanprover/lean4:v4.30.0" — extract version
        if ":" in raw:
            version = raw.split(":")[-1]
        else:
            version = raw
        # Strip leading "v" if present (elan dirs: "4.30.0", not "v4.30.0")
        return version.lstrip("v")
    except OSError:
        return _DEFAULT_LEAN_VERSION


def _find_lean_binary(version: str) -> Path:
    """Find the ``lean`` binary for *version* in elan's toolchains.

    Fallback patterns:
        1. ``~/.elan/toolchains/{version}/bin/lean``
        2. ``~/.elan/toolchains/{version}/bin/lean`` (full tag format)
        3. ``~/.elan/toolchains/stable/bin/lean``
    """
    home = Path.home()
    toolchains = home / ".elan" / "toolchains"

    # Exact version
    candidates = [
        toolchains / version / "bin" / "lean",
        toolchains / f"leanprover--lean4---v{version}" / "bin" / "lean",
        toolchains / "stable" / "bin" / "lean",
    ]
    for p in candidates:
        if p.is_file():
            return p
    # Last resort: return the first guess anyway
    return candidates[0]


def _find_lake_binary(version: str) -> Path:
    """Find the ``lake`` binary — analog to _find_lean_binary."""
    home = Path.home()
    toolchains = home / ".elan" / "toolchains"

    candidates = [
        toolchains / version / "bin" / "lake",
        toolchains / f"leanprover--lean4---v{version}" / "bin" / "lake",
        toolchains / "stable" / "bin" / "lake",
    ]
    for p in candidates:
        if p.is_file():
            return p
    return candidates[0]


def _count_mathlib_oleans(project_dir: Path) -> int:
    """Count .olean files in the Mathlib cache (fast, skips hidden dirs)."""
    mathlib_dir = project_dir / ".lake" / "packages" / "mathlib"
    if not mathlib_dir.is_dir():
        # Fallback: old "lake-packages" naming
        mathlib_dir = project_dir / "lake-packages" / "mathlib"
        if not mathlib_dir.is_dir():
            return 0
    try:
        result = subprocess.run(
            ["find", str(mathlib_dir), "-name", "*.olean", "-type", "f"],
            capture_output=True,
            text=True,
            timeout=5,
        )
        if result.returncode == 0:
            return len(result.stdout.strip().splitlines())
        return 0
    except (subprocess.TimeoutExpired, OSError):
        return 0


def _measure_mathlib_size(project_dir: Path) -> float:
    """Measure on-disk size of the Mathlib cache in GB."""
    mathlib_dir = project_dir / ".lake" / "packages" / "mathlib"
    if not mathlib_dir.is_dir():
        mathlib_dir = project_dir / "lake-packages" / "mathlib"
        if not mathlib_dir.is_dir():
            return 0.0
    try:
        result = subprocess.run(
            ["du", "-sk", str(mathlib_dir)],
            capture_output=True,
            text=True,
            timeout=5,
        )
        if result.returncode == 0:
            kb = int(result.stdout.strip().split()[0])
            return round(kb / 1_048_576, 1)  # KB → GB
        return 0.0
    except (subprocess.TimeoutExpired, OSError):
        return 0.0


def _test_compile_channel(project_dir: Path, lean_bin: Path, lake_bin: Path) -> str:
    """Test which compile channel works: ``lake_env`` or ``bare_lean``.

    Tries ``lake env lean --stdin`` first (with Mathlib).  Falls back to
    ``lean --stdin`` (no Mathlib) if the lake env path fails.
    """
    # Test lake_env channel
    if project_dir.is_dir() and lake_bin.is_file() and lean_bin.is_file():
        try:
            proc = subprocess.run(
                [str(lake_bin), "env", str(lean_bin), "--stdin"],
                input="theorem t : True := trivial",
                capture_output=True,
                text=True,
                timeout=10,
                cwd=str(project_dir),
            )
            if proc.returncode == 0:
                return "lake_env"
        except (subprocess.TimeoutExpired, OSError):
            pass

    # Fallback: bare lean
    if lean_bin.is_file():
        try:
            proc = subprocess.run(
                [str(lean_bin), "--stdin"],
                input="theorem t : True := trivial",
                capture_output=True,
                text=True,
                timeout=10,
            )
            if proc.returncode == 0:
                return "bare_lean"
        except (subprocess.TimeoutExpired, OSError):
            pass

    return "lake_env"  # default guess


def discover_lean(project_dir: str | Path | None = None) -> LeanConfig:
    """Auto-discover the Lean/Mathlib toolchain from the filesystem.

    Scans:
    - The Lean project directory for ``lean-toolchain`` and Mathlib cache
    - ``~/.elan/toolchains/`` for matching binary
    - Tests compile channel availability

    Parameters
    ----------
    project_dir : str or Path, optional
        Path to scan.  Defaults to ``~/lean-paper-plane``.

    Returns
    -------
    LeanConfig
        Populated from filesystem discovery.
    """
    project_path = Path(project_dir) if project_dir else _DEFAULT_PROJECT

    # Phase 1: Read lean-toolchain
    version = _read_lean_toolchain(project_path)

    # Phase 2: Find binaries
    lean_bin = _find_lean_binary(version)
    lake_bin = _find_lake_binary(version)

    # Phase 3: Count mathlib oleans
    olean_count = _count_mathlib_oleans(project_path)
    mathlib_size = _measure_mathlib_size(project_path)

    # Phase 4: Test compile channel
    channel = _test_compile_channel(project_path, lean_bin, lake_bin)
    fallback = ["bare_lean"] if channel != "bare_lean" else []

    return LeanConfig(
        version=version,
        project_path=project_path,
        lean_bin=lean_bin,
        lake_bin=lake_bin,
        olean_count=olean_count,
        mathlib_size_gb=mathlib_size,
        compile_channel=channel,
        compile_fallback=fallback,
        _source="(auto-discovered)",
    )


# ── Public loading API ──────────────────────────────────────────


_lean_config_cache: LeanConfig | None = None


def load_lean_config(force_discover: bool = False) -> LeanConfig:
    """Load Lean/Mathlib configuration from the best available source.

    Loading chain:
        1. ``omega.toml [lean]`` section (generated by ``omega init``)
        2. Auto-discovery from filesystem
        3. ``LeanConfig()`` defaults (hardcoded fallbacks)

    Returns
    -------
    LeanConfig
        Cached across calls unless *force_discover* is True.
    """
    global _lean_config_cache

    if _lean_config_cache is not None and not force_discover:
        return _lean_config_cache

    # 1. Try config file
    config_path = _find_config_file()
    if config_path:
        lean_data = _read_lean_from_toml(config_path)
        if lean_data is not None:
            cfg = LeanConfig.from_dict(lean_data, source=config_path)
            # Validate — if the config file points to valid paths, use it
            if cfg.project_exists() and cfg.binaries_ok():
                _lean_config_cache = cfg
                return cfg
            # Otherwise, warn and fall through to discovery

    # 2. Auto-discover
    discovered = discover_lean()
    _lean_config_cache = discovered
    return discovered


def reset_lean_config_cache() -> None:
    """Clear the cached LeanConfig (useful in tests)."""
    global _lean_config_cache
    _lean_config_cache = None


def discover_and_write_lean_config(config_path: str | None = None) -> LeanConfig:
    """Discover the Lean toolchain and write the ``[lean]`` section to ``omega.toml``.

    Parameters
    ----------
    config_path : str, optional
        Target file path.  Defaults to the first found config file,
        or ``omega.toml`` in CWD.

    Returns
    -------
    LeanConfig
        The discovered (and now persisted) configuration.

    Raises
    ------
    FileNotFoundError
        If *config_path* doesn't exist and CWD has no omega.toml.
    """
    # Find or create target file
    target = config_path or _find_config_file() or "omega.toml"
    target_path = Path(target)

    if not target_path.is_file():
        raise FileNotFoundError(
            f"Config file not found: {target}.  Run ``omega init`` first."
        )

    # Discover
    cfg = discover_lean()

    # Read existing content, append [lean] section
    existing = target_path.read_text(encoding="utf-8")
    section = cfg.to_toml_section()

    # Remove old [lean] section if present
    import re

    # Match from "[lean]" (or "# ── Lean") through the next top-level section
    pattern = re.compile(
        r"(?:^|\n)# ── Lean.*?(?=\n\[|$)",
        re.DOTALL,
    )
    cleaned = pattern.sub("", existing).rstrip() + "\n\n" + section

    target_path.write_text(cleaned, encoding="utf-8")
    reset_lean_config_cache()

    return cfg
