#!/usr/bin/env python3
"""T2 Real Compile — compiles Lean code using lake env lean --stdin.

Bypasses MCP to compile arbitrary Lean code including Mathlib-dependent
theorems, using the existing Mathlib cache in lean-paper-plane project.

Paths are loaded from ``omega.toml [lean]`` (generated by ``omega init``),
with auto-discovery fallback — never hardcoded.

Usage
-----
    from omega.verify.t2_real import make_real_compile_callback
    from omega.verify.t2_lean import verify as t2_verify

    compile_fn = make_real_compile_callback()
    result = t2_verify("theorem t : True := trivial", compile_fn=compile_fn)
    assert result.verified
"""

from __future__ import annotations

import re
import subprocess
from collections.abc import Callable
from pathlib import Path
from typing import Any

from omega.resource.lean_config import load_lean_config

# ── Config loading (single source of truth) ─────────────────────


def _get_lean_config() -> tuple[Path, Path, Path]:
    """Load Lean/Mathlib paths from the config chain.

    Returns
    -------
    tuple[Path, Path, Path]
        ``(project_dir, lean_bin, lake_bin)`` — ready for subprocess.

    Never raises: falls back to ``~/lean-paper-plane`` / ``~/.elan/...``
    if discovery fails.
    """
    cfg = load_lean_config()
    return cfg.project_path, cfg.lean_bin, cfg.lake_bin


# ── diagnostic parser ──────────────────────────────────────────


# Matches: <stdin>:<line>:<col>: <severity>: <message>
# Example: <stdin>:4:27: warning: unused variable `h`
_DIAG_RE = re.compile(
    r"^"
    r"(?P<file>.+?):"  # file (e.g., <stdin>)
    r"(?P<line>\d+):"  # line number
    r"(?P<col>\d+):\s"  # column
    r"(?P<severity>(?:warning|error|info|note)):\s"  # severity
    r"(?P<message>.+)"  # message
    r"$"
)


def parse_lean_diagnostics(stderr: str) -> list[dict[str, Any]]:
    """Parse stderr output from ``lean --stdin`` into MCP-style diagnostics list.

    The ``lean --stdin`` output is line-oriented::

        <stdin>:<line>:<col>: warning: unused variable `x`
        <stdin>:13:9: error: unsolved goals

    Returns
    -------
    list[dict]
        Each dict has keys: ``message``, ``severity``, ``line``, ``column``.
        Non-diagnostic lines are captured as info-level diagnostics.
    """
    diagnostics: list[dict[str, Any]] = []
    for raw_line in stderr.strip().split("\n"):
        line = raw_line.strip()
        if not line:
            continue
        m = _DIAG_RE.match(line)
        if m:
            diagnostics.append(
                {
                    "message": m.group("message"),
                    "severity": m.group("severity"),
                    "line": int(m.group("line")),
                    "column": int(m.group("col")),
                }
            )
        else:
            # Non-diagnostic lines, e.g. Lean info messages
            diagnostics.append(
                {
                    "message": line,
                    "severity": "info",
                    "line": 1,
                    "column": 1,
                }
            )
    return diagnostics


# ── compile callback ───────────────────────────────────────────


def real_compile_callback(
    code: str,
    timeout: int = 60,
    project_dir: Path | None = None,
    lean_bin: Path | None = None,
    lake_bin: Path | None = None,
) -> dict[str, Any]:
    """Compile Lean code using ``lake env lean --stdin`` with Mathlib.

    Writes ``code`` to stdin of the Lean compiler running inside the
    Lean project environment, which has Mathlib cached.  Paths are loaded
    from ``omega.toml [lean]`` by default.

    Parameters
    ----------
    code : str
        Self-contained Lean code (must include ``import Mathlib`` if needed).
        ``format_code()`` from ``t2_lean`` will prepend ``import Mathlib``
        automatically if import-less code is passed.
    timeout : int
        Max seconds for compilation (default 60).
    project_dir : Path, optional
        Override the Lean project directory.  Uses config if omitted.
    lean_bin : Path, optional
        Override the Lean binary path.  Uses config if omitted.
    lake_bin : Path, optional
        Override the Lake binary path.  Uses config if omitted.

    Returns
    -------
    dict
        Shape compatible with ``parse_diagnostics`` from ``t2_lean.py``:
        ``{"diagnostics": [...], "exit_code": N, "stdout": "..."}``.
    """
    # Resolve paths from config if not explicitly passed
    if project_dir is None or lean_bin is None or lake_bin is None:
        _project_dir, _lean_bin, _lake_bin = _get_lean_config()
        project_dir = project_dir or _project_dir
        lean_bin = lean_bin or _lean_bin
        lake_bin = lake_bin or _lake_bin

    if not project_dir.exists():
        return {
            "diagnostics": [
                {
                    "message": f"Project directory not found: {project_dir}",
                    "severity": "error",
                    "line": 1,
                    "column": 1,
                }
            ],
            "exit_code": -1,
            "stdout": "",
        }

    if not lake_bin.exists():
        return {
            "diagnostics": [
                {
                    "message": f"lake binary not found: {lake_bin}",
                    "severity": "error",
                    "line": 1,
                    "column": 1,
                }
            ],
            "exit_code": -2,
            "stdout": "",
        }

    cmd = [str(lake_bin), "env", str(lean_bin), "--stdin"]

    try:
        proc = subprocess.run(
            cmd,
            input=code,
            capture_output=True,
            text=True,
            cwd=str(project_dir),
            timeout=timeout,
        )
    except subprocess.TimeoutExpired:
        return {
            "diagnostics": [
                {
                    "message": f"Lean compilation timed out after {timeout}s",
                    "severity": "error",
                    "line": 1,
                    "column": 1,
                }
            ],
            "exit_code": -3,
            "stdout": "",
        }

    stderr = proc.stderr or ""
    stdout = proc.stdout or ""

    # ``lean --stdin`` outputs diagnostics to stdout, not stderr.
    all_output = stdout + "\n" + stderr
    diagnostics = parse_lean_diagnostics(all_output)

    return {
        "diagnostics": diagnostics,
        "exit_code": proc.returncode,
        "stdout": stdout[:500] if stdout else "",
    }


def make_real_compile_callback(
    project_dir: str | Path | None = None,
    timeout: int = 60,
) -> Callable[[str], dict[str, Any]]:
    """Return a ``compile_fn`` for ``t2_lean.verify()``.

    The returned callable uses ``lake env lean --stdin`` to compile
    Lean code against a real Mathlib cache.  Paths are loaded from
    ``omega.toml [lean]`` by default.

    Parameters
    ----------
    project_dir : str or Path, optional
        Path to a Lean project with cached Mathlib.  If omitted, loads
        from ``omega.toml [lean]`` (generated by ``omega init``).
    timeout : int
        Max seconds per compilation (default 60).

    Returns
    -------
    Callable[[str], dict]
        Suitable as ``compile_fn`` for ``t2_lean.verify()`` or
        ``T2OnlineRunner``.
    """
    if project_dir is not None:
        p = Path(project_dir)
        _project_dir, _lean_bin, _lake_bin = _get_lean_config()
        explicit_dir = p
        explicit_lean = _lean_bin
        explicit_lake = _lake_bin
    else:
        explicit_dir = None
        explicit_lean = None
        explicit_lake = None

    def _compile(code: str) -> dict[str, Any]:
        return real_compile_callback(
            code,
            timeout=timeout,
            project_dir=explicit_dir,
            lean_bin=explicit_lean,
            lake_bin=explicit_lake,
        )

    return _compile
