#!/usr/bin/env python3
"""Omega CLI — ``omega init``, ``omega config``, and ``omega prove``.

Entry point::

    def main():
        typer_app()
"""

from __future__ import annotations

import json
import sys
from pathlib import Path
from typing import Any

import typer

from omega.resource.config import (
    BudgetConfig,
    _find_config_file,
    load_config,
    reset_config_cache,
)

app = typer.Typer(
    name="omega",
    help="Ω-Architect — Open Formal Theorem Proving for Physics & Quantum",
    add_completion=False,
)

# ── Template content ────────────────────────────────────────────


def _default_template() -> str:
    """Generate a commented omega.toml template."""
    return """# =============================================================================
# Omega Budget Configuration (auto-generated by ``omega init``)
# =============================================================================
# Edit this file to control resource allocation per theorem.
#
# Loading order (later overrides earlier):
#   1. Code defaults (BudgetConfig class)
#   2. This file
#   3. OMEGA_* environment variables
#   4. --budget-* CLI flags
# =============================================================================

# ── Budget Dimensions ──────────────────────────────────────────
[budget]
# Maximum tokens across all models (1M ≈ ~$0.57 DeepSeek, ~$18 Claude Sonnet)
max_tokens = 1_000_000

# Maximum USD cost (paid providers only; free models skip cost tracking)
max_cost_usd = 0.50

# Maximum wall-clock seconds per theorem
max_time_s = 300.0

# Maximum T2 compile attempts
max_attempts = 50

# Minimum proposer confidence (0.0 = accept all, 1.0 = only high-confidence)
min_confidence = 0.3

# ── Epoch (Self-Correction Round) Tracking ─────────────────────
[budget.epochs]
# Maximum correction rounds (initial sampling counts as epoch 1)
max_epochs = 5

# Convergence threshold: if average error-reduction rate < this over window,
# we declare "converged" and stop (avoids endless corrections)
convergence_threshold = 0.1

# Sliding window for convergence detection (must be >= 2)
window = 3

# ── Research Phase Budget ──────────────────────────────────────
[research]
# Tokens reserved for knowledge research (arXiv papers, GitHub code analysis)
max_tokens = 50_000

# Seconds reserved for research phase
max_time_s = 60.0

# Maximum related papers to retrieve
max_papers = 5

# Maximum GitHub Lean4 code results to retrieve
max_github_results = 10

# ── Model Pricing ──────────────────────────────────────────────
[models]
# Free-model prefixes — these skip cost tracking
free = ["ollama/", "local/"]

# Paid model prices (USD per token).
# Add your own models here; unknown models are treated as free.
"""
    for model_id, prices in dict(BudgetConfig().model_prices).items():
        in_rate = prices.get("input_per_token", 0)
        out_rate = prices.get("output_per_token", 0)
        lines = []
        lines.append(f'[models."{model_id}"]')
        lines.append(f"input_per_token = {in_rate!r}    # ${in_rate * 1e6:.2f}/M tokens")
        lines.append(f"output_per_token = {out_rate!r}   # ${out_rate * 1e6:.2f}/M tokens")
        lines.append("")
        section = "\n".join(lines)
        # indent
        section = "\n".join(section.split("\n"))

    return _default_template.__doc__  # type: ignore[return-value]


def _config_template(cfg: BudgetConfig | None = None) -> str:
    """Return a commented TOML template string."""
    if cfg is None:
        cfg = BudgetConfig()
    buf: list[str] = []

    buf.append("# Ω-Architect Budget Configuration")
    buf.append("# Uncomment and edit values to override defaults.")
    buf.append("")

    # ── Budget ──
    buf.append("[budget]")
    buf.append(f"# max_tokens = {cfg.max_tokens}    # 1M = ~$0.57 DeepSeek, ~$18 Claude")
    buf.append(f"# max_cost_usd = {cfg.max_cost_usd}")
    buf.append(f"# max_time_s = {cfg.max_time_s}")
    buf.append(f"# max_attempts = {cfg.max_attempts}")
    buf.append(f"# min_confidence = {cfg.min_confidence}")
    buf.append("")
    buf.append("[budget.epochs]")
    buf.append(f"# max_epochs = {cfg.epochs.max_epochs}")
    buf.append(f"# convergence_threshold = {cfg.epochs.convergence_threshold}")
    buf.append(f"# window = {cfg.epochs.window}")
    buf.append("")

    # ── Research ──
    buf.append("[research]")
    buf.append(f"# max_tokens = {cfg.research_max_tokens}")
    buf.append(f"# max_time_s = {cfg.research_max_time_s}")
    buf.append(f"# max_papers = {cfg.max_papers}")
    buf.append(f"# max_github_results = {cfg.max_github_results}")
    buf.append("")

    # ── Models ──
    buf.append("[models]")
    buf.append(f"free = {json.dumps(cfg.free_models)}")
    buf.append("")
    for model_id, prices in cfg.model_prices.items():
        in_rate = prices.get("input_per_token", 0)
        out_rate = prices.get("output_per_token", 0)
        buf.append(f'[models."{model_id}"]')
        buf.append(f"# input_per_token = {in_rate!r}    # ${in_rate * 1e6:.2f}/M")
        buf.append(f"# output_per_token = {out_rate!r}   # ${out_rate * 1e6:.2f}/M")
        buf.append("")

    return "\n".join(buf)


# ── CLI Commands ────────────────────────────────────────────────


@app.callback()
def main_callback(
    ctx: typer.Context,
    config: str = typer.Option(
        "",
        "--config",
        "-c",
        help="Path to omega.toml config file",
        envvar="OMEGA_CONFIG",
    ),
) -> None:
    """Ω-Architect CLI — resource configuration and theorem proving."""
    ctx.ensure_object(dict)
    ctx.obj["config_path"] = config


@app.command("init")
def init_cmd(
    force: bool = typer.Option(False, "--force", "-f", help="Overwrite existing file"),
    output: str = typer.Option(
        "omega.toml",
        "--output",
        "-o",
        help="Output path for the config template",
    ),
    skip_lean: bool = typer.Option(
        False,
        "--skip-lean",
        help="Skip Lean/Mathlib discovery (budget config only)",
    ),
) -> None:
    """Generate a commented omega.toml configuration template with lean discovery.

    Phase 1: Writes the budget/resource config template.
    Phase 2: Auto-discovers Lean/Mathlib toolchain and writes ``[lean]`` section.
    """
    from omega.resource.lean_config import discover_and_write_lean_config

    out_path = Path(output)
    if out_path.exists() and not force:
        typer.echo(f"❌ {out_path} already exists. Use --force to overwrite.")
        raise typer.Exit(1)

    # ── Phase 1: Budget template ──
    template = _config_template()
    out_path.write_text(template, encoding="utf-8")
    typer.echo(f"✅ Phase 1 — Generated budget template: {out_path}")

    # ── Phase 2: Lean/Mathlib discovery ──
    if skip_lean:
        typer.echo("⏭️  Phase 2 — Lean discovery skipped (--skip-lean)")
    else:
        typer.echo("")
        typer.echo("🔍 Phase 2 — Discovering Lean/Mathlib toolchain...")
        try:
            cfg = discover_and_write_lean_config(str(out_path))
            typer.echo(f"   → Lean version:        {cfg.version}")
            typer.echo(f"   → Project path:        {cfg.project_path}")
            typer.echo(f"   → Lean binary:         {cfg.lean_bin}")
            typer.echo(f"   → Lake binary:         {cfg.lake_bin}")
            typer.echo(f"   → Mathlib oleans:      {cfg.olean_count:,}")
            typer.echo(f"   → Mathlib size:        {cfg.mathlib_size_gb:.1f} GB")
            typer.echo(f"   → Compile channel:     {cfg.compile_channel}")
            if cfg.compile_fallback:
                typer.echo(f"   → Fallback channels:   {cfg.compile_fallback}")
            typer.echo(f"✅ Lean discovery written to {out_path}")
        except FileNotFoundError as exc:
            typer.echo(f"⚠️  {exc}")
            typer.echo("   Run again with an existing config file, or run without --output.")
        except Exception as exc:
            typer.echo(f"⚠️  Lean discovery failed: {exc}")
            typer.echo("   The [lean] section was not written.  "
                       "T2 compilation will use hardcoded fallbacks.")

    typer.echo("")
    typer.echo("Done.  Next steps:")
    typer.echo("  omega config show    # verify loaded config (budget + lean)")
    typer.echo('  omega prove "theorem t : True := trivial"  # test T2 compile')


@app.command("config")
def config_cmd(
    ctx: typer.Context,
    action: str = typer.Argument(
        "show",
        help="Action: show / set / path",
    ),
    key: str = typer.Option("", "--key", "-k", help="Dot-path key (e.g., budget.max_tokens)"),
    value: str = typer.Option("", "--value", "-v", help="Value to set"),
) -> None:
    """View or modify Omega configuration.

    Actions:

    **show** (default) — Display current config with source annotation.

    **set** — Save a key=value to the config file (requires --key and --value).

    **path** — Show config file discovery path.
    """
    cfg_path = ctx.obj.get("config_path", "")

    if action == "path":
        found = _find_config_file()
        if found:
            typer.echo(f"📄 Config file: {found}")
        else:
            typer.echo("📄 No config file found (using defaults)")
        typer.echo(f"   OMEGA_CONFIG env: {cfg_path or '(not set)'}")
        typer.echo(f"   CWD:              {Path.cwd()}")
        return

    if action == "set":
        if not key:
            typer.echo("❌ --key is required for 'set' action")
            raise typer.Exit(1)
        if not value:
            typer.echo("❌ --value is required for 'set' action")
            raise typer.Exit(1)

        # Find or create config file
        config_file = cfg_path or _find_config_file() or "omega.toml"
        cfg_path_obj = Path(config_file)

        if cfg_path_obj.is_file():
            current = cfg_path_obj.read_text(encoding="utf-8")
        else:
            current = _config_template()
            cfg_path_obj.parent.mkdir(parents=True, exist_ok=True)

        # Parse key into TOML section path
        parts = key.split(".")
        if len(parts) >= 2:
            section = ".".join(parts[:-1])
            k = parts[-1]
            # Try to find and uncomment the line
            import re

            # Match commented or uncommented key
            pattern = re.compile(r"^(#\s*)?(" + re.escape(k) + r")\s*=\s*.*$", re.MULTILINE)
            # Parse value as number if possible
            try:
                parsed_val = json.loads(value)
            except (json.JSONDecodeError, ValueError):
                parsed_val = value

            # Format value
            if isinstance(parsed_val, bool):
                val_str = "true" if parsed_val else "false"
            elif isinstance(parsed_val, (int, float)):
                val_str = str(parsed_val)
            elif isinstance(parsed_val, list):
                val_str = json.dumps(parsed_val)
            else:
                val_str = f'"{parsed_val}"'

            replacement = f"{k} = {val_str}"
            if pattern.search(current):
                updated = pattern.sub(replacement, current)
            else:
                # Append to the right section
                section_header = f"[{section}]"
                if section_header in current:
                    # Find section and add after it
                    updated = current.replace(section_header, f"{section_header}\n{replacement}")
                else:
                    updated = current + f"\n[{section}]\n{replacement}\n"

            cfg_path_obj.write_text(updated, encoding="utf-8")
            reset_config_cache()
            typer.echo(f"✅ Set {key} = {val_str} in {cfg_path_obj}")
        else:
            typer.echo(
                "❌ Key must have at least two dot-separated parts (e.g., budget.max_tokens)"
            )
            raise typer.Exit(1)
        return

    # Default: show
    reset_config_cache()
    cfg = load_config(config_path=cfg_path)

    typer.echo("=" * 60)
    typer.echo("Ω-Architect Configuration")
    typer.echo("=" * 60)
    if cfg._source_file:
        typer.echo(f"📄 Source: {cfg._source_file}")
    else:
        typer.echo("📄 Source: defaults (no config file)")
    typer.echo("")

    # Display as formatted key=value
    flat = _flatten_config(cfg)
    for key_path, val in sorted(flat.items()):
        typer.echo(f"  {key_path:45s} = {val!r}")

    # Show Lean config if available
    try:
        from omega.resource.lean_config import load_lean_config

        lean_cfg = load_lean_config()
        if lean_cfg.project_exists() or lean_cfg.binaries_ok():
            typer.echo("")
            typer.echo("─" * 60)
            typer.echo("Lean/Mathlib Toolchain")
            typer.echo("─" * 60)
            typer.echo(f"  Lean version:              {lean_cfg.version}")
            typer.echo(f"  Project path:              {lean_cfg.project_path}")
            typer.echo(f"  Lean binary:               {lean_cfg.lean_bin}")
            typer.echo(f"  Lake binary:               {lean_cfg.lake_bin}")
            typer.echo(f"  Mathlib oleans:            {lean_cfg.olean_count:,}")
            typer.echo(f"  Mathlib size:              {lean_cfg.mathlib_size_gb:.1f} GB")
            typer.echo(f"  Compile channel:           {lean_cfg.compile_channel}")
            typer.echo(f"  Source:                    {lean_cfg._source or '(defaults)'}")
            typer.echo(f"  Status:                    {lean_cfg.summary()}")
    except ImportError:
        pass

    typer.echo("")
    typer.echo("To change: edit omega.toml or use `omega config set --key ... --value ...`")


# ── Helpers ─────────────────────────────────────────────────────


def _flatten_config(cfg: BudgetConfig) -> dict[str, Any]:
    """Flatten a BudgetConfig into dot-path key=value pairs."""
    result: dict[str, Any] = {}

    # Budget dimensions
    b = {
        "budget.max_tokens": cfg.max_tokens,
        "budget.max_cost_usd": cfg.max_cost_usd,
        "budget.max_time_s": cfg.max_time_s,
        "budget.max_attempts": cfg.max_attempts,
        "budget.min_confidence": cfg.min_confidence,
        "budget.epochs.max_epochs": cfg.epochs.max_epochs,
        "budget.epochs.convergence_threshold": cfg.epochs.convergence_threshold,
        "budget.epochs.window": cfg.epochs.window,
    }

    # Research
    r = {
        "research.max_tokens": cfg.research_max_tokens,
        "research.max_time_s": cfg.research_max_time_s,
        "research.max_papers": cfg.max_papers,
        "research.max_github_results": cfg.max_github_results,
    }

    # Models
    m: dict[str, Any] = {"models.free": list(cfg.free_models)}
    for model_id, prices in cfg.model_prices.items():
        short = model_id.replace("/", ".")
        m[f"models.{short}.input_per_token"] = prices.get("input_per_token", 0)
        m[f"models.{short}.output_per_token"] = prices.get("output_per_token", 0)

    result.update(b)
    result.update(r)
    result.update(m)
    return result


# ── Entry point ─────────────────────────────────────────────────


def main() -> None:
    app()


if __name__ == "__main__":
    main()


# ── Run command ────────────────────────────────────────────────


@app.command("run")
def run_cmd(
    research_goal: str = typer.Argument(
        ..., help="Research goal description, e.g. 'Formalize NV spin Hamiltonian'"
    ),
    time_hours: float = typer.Option(
        2.0, "--time", "-t", help="Max run time in hours (2, 4, 8, 12, etc.)"
    ),
    model: str = typer.Option("local/default", "--model", "-m", help="LLM model ID to use"),
    checkpoint: str = typer.Option(
        "", "--resume", "-r", help="Path to checkpoint file to resume from"
    ),
) -> None:
    """Run autonomous proof search for a research goal.

    Runs unattended for *--time* hours, proving theorems related to the
    research goal. Checkpoints are saved periodically — use ``--resume``
    to continue from a previous run.

    Example:
        omega run "Formalize NV center spin Hamiltonian" --time 4
        omega run "Prove Maxwell equations in Lean" --time 8 --model deepseek/deepseek-chat
        omega run "Continue previous session" --resume ~/.omega/checkpoints/checkpoint_20260606_120000.json
    """
    from omega.runner import OmegaRunner, TheoremSpec

    # Build theorem list from the research goal keywords
    # For now, we create a default theorem based on the goal name
    theorems = [
        TheoremSpec(
            header=f"theorem research_goal_{i} : True :=",
            description=research_goal,
            priority=1,
            domain="general",
        )
        for i in range(1)
    ]

    time_budget_s = time_hours * 3600.0
    typer.echo(f"🚀 Starting {time_hours}h autonomous proof search")
    typer.echo(f"   Goal: {research_goal}")
    typer.echo(f"   Model: {model}")
    typer.echo(f"   Budget: {time_budget_s:.0f}s wall clock")
    typer.echo("")

    runner = OmegaRunner(
        time_budget_s=time_budget_s,
        model_id=model,
    )

    report = runner.run(
        research_goal=research_goal,
        theorems=theorems,
        resume_checkpoint=checkpoint,
    )

    typer.echo(report.summary())
    typer.echo("")

    # Show allocator provenance
    provenance = runner._allocator.provenance_summary()
    typer.echo(provenance)

    # Show cost report
    cost = runner._allocator.cost_report()
    typer.echo("\n💰 Cost breakdown:")
    typer.echo(
        f"   Pro (blueprint):  ${cost['pro_spent']:.4f} / ${cost['pro_remaining'] + cost['pro_spent']:.2f} budget"
    )
    typer.echo(
        f"   Flash (append):   ${cost['flash_spent']:.4f} / ${cost['flash_remaining'] + cost['flash_spent']:.2f} budget"
    )
    typer.echo(f"   Total:            ${cost['total_usd']:.4f}")

    # Show dynamic tok/s if local model was used
    tok_s = runner._bt.dynamic_tok_s()
    if tok_s > 0:
        typer.echo(f"⚡ Dynamic tok/s: {tok_s:.1f}")


# ── Benchmark group ────────────────────────────────────────────

_benchmark_app = typer.Typer(name="benchmark", help="Benchmark: hardware (tok/s) or theorems (T2 pass rate).")


@_benchmark_app.command("hardware")
def benchmark_hardware_cmd(
    refresh: bool = typer.Option(False, "--refresh", "-r", help="Re-run benchmarks"),
) -> None:
    """Benchmark local ollama models and show token throughput."""
    from omega.resource.benchmark import discover_and_benchmark, load_benchmark

    typer.echo("=" * 60)
    typer.echo("Ω-Architect Hardware Benchmark")
    typer.echo("=" * 60)

    if refresh:
        data = discover_and_benchmark()
        data.save()
    else:
        data = load_benchmark(refresh=False)

    typer.echo(f"Measured at: {data.measured_at}")
    typer.echo(f"Hardware:    {data.hardware}")
    typer.echo("")
    typer.echo(f"{'Model':30s} {'tok/s':>8} {'tok/call':>10} {'12h tokens':>14}")
    typer.echo("-" * 62)
    for name, r in data.models.items():
        tok_s = r.avg_tok_s
        tok_call = r.avg_tokens_per_call
        est_12h = int(tok_s * 43200)
        typer.echo(f"{name:30s} {tok_s:>8.1f} {tok_call:>10} {est_12h:>14,}")

    typer.echo("")
    typer.echo('Tip: run `omega run "goal" --time 4` to use these rates automatically.')


@_benchmark_app.command("theorems")
def benchmark_theorems_cmd(
    mode: str = typer.Option(
        "quick",
        "--mode",
        "-M",
        help="Test profile: smoke (Tier1, ~$0.02) | quick (Tier1-3抽样, ~$0.10) | full (全量, ~$0.30)",
    ),
    tiers: str = typer.Option(
        "",
        "--tiers",
        "-t",
        help="Tier range (1, 1-3, 4, etc.) — 优先级低于 --mode",
    ),
    model: str = typer.Option(
        "deepseek/deepseek-v4-flash",
        "--model",
        "-m",
        help="Model ID for proof generation",
    ),
    samples: int = typer.Option(
        4,
        "--samples",
        "-s",
        help="Number of parallel samples per round",
    ),
    rounds: int = typer.Option(
        2,
        "--rounds",
        "-r",
        help="Max self-correction rounds",
    ),
    timeout: int = typer.Option(
        120,
        "--timeout",
        help="T2 compile timeout in seconds",
    ),
    output: str = typer.Option(
        "",
        "--output",
        "-o",
        help="Save results to JSON file",
    ),
    yes: bool = typer.Option(
        False,
        "--yes",
        "-y",
        help="Skip confirmation prompt",
    ),
) -> None:
    """Run theorem proof benchmark with budget-aware profiles.

    Three profiles control how many theorems are sampled and what
    the cost ceiling is:

      \b
      - smoke:   Tier 1 only (5 theorems), ~$0.02
      - quick:   Tier 1-3 sampling (12 theorems), ~$0.10  [default]
      - full:    Tier 1-4 all (30 theorems), ~$0.30

    Examples::

        omega benchmark theorems                          # quick mode
        omega benchmark theorems --mode smoke             # 快速验证
        omega benchmark theorems --mode full --yes        # 全量, 跳过确认
        omega benchmark theorems --mode quick --output results.json
    """
    from omega.benchmark.suite import BenchmarkSuite

    typer.echo("=" * 60)
    typer.echo("Ω-Architect Theorem Benchmark")
    typer.echo("=" * 60)
    typer.echo(f"Model:  {model}")
    typer.echo(f"Tiers:  {tiers}")
    typer.echo(f"Config: {samples} samples/round × {rounds} correction rounds")
    typer.echo("")

    suite = BenchmarkSuite(
        model_id=model,
        timeout=timeout,
        samples=samples,
        rounds=rounds,
    )

    results = suite.run(profile=mode if not tiers else None, tiers=tiers or None)

    typer.echo("")
    typer.echo(results.report())

    if output:
        out_path = Path(output)
        out_path.write_text(
            __import__("json").dumps(results.to_json(), indent=2),
            encoding="utf-8",
        )
        typer.echo(f"\n📄 Results saved to {out_path}")

    # --yes 跳过确认，但不对结果做自动 pass/fail 判断
    if yes:
        total_ok = sum(1 for r in results.results if r.succeeded)
        total_n = len(results.results)
        typer.echo(f"\n{'=' * 50}")
        typer.echo(f"  Done: {total_ok}/{total_n} passed ({total_ok / max(1, total_n) * 100:.0f}%)")
        typer.echo(f"{'=' * 50}")


@app.command("prove")
def prove_cmd(
    theorem_header: str = typer.Argument(
        ...,
        help="Lean 4 theorem header, e.g. 'theorem add_zero (n : ℕ) : n + 0 = n :='",
    ),
    model: str = typer.Option(
        "deepseek/deepseek-v4-flash",
        "--model",
        "-m",
        help="Model ID (deepseek/..., local/..., ollama/...)",
    ),
    imports: str = typer.Option(
        "import Mathlib",
        "--imports",
        "-i",
        help="Extra imports (use '' for none)",
    ),
    samples: int = typer.Option(
        4,
        "--samples",
        "-s",
        help="Number of parallel samples per round",
    ),
    rounds: int = typer.Option(
        2,
        "--rounds",
        "-r",
        help="Max self-correction rounds",
    ),
    timeout: int = typer.Option(
        120,
        "--timeout",
        "-t",
        help="T2 compile timeout in seconds",
    ),
    mode: str = typer.Option(
        "auto",
        "--mode",
        "-M",
        help="Strategy mode: auto (ModeRouter), dfs, beam, hybrid",
    ),
) -> None:
    """Prove a single Lean 4 theorem: generate → compile → verified proof.

    Uses ModeRouter for strategy auto-selection, or explicit mode via --mode.
    """
    from omega.resource.lean_config import load_lean_config

    lean_cfg = load_lean_config()
    if not lean_cfg.binaries_ok():
        typer.echo("❌ Lean/Mathlib toolchain not available. Run `omega init --force` first.")
        raise typer.Exit(1)

    header = theorem_header.strip()
    mode_lower = mode.lower()

    # ── ModeRouter auto-selection ──
    if mode_lower == "auto":
        from omega.engine.router import ModeRouter, RoutingContext, ResourceProfile
        router = ModeRouter()
        ctx = RoutingContext(theorem_header=header, resource_profile=ResourceProfile.API_ONLY)
        decision = router.route(ctx)
        mode_lower = decision.strategy_name
        typer.echo(f"\n🔀 ModeRouter → {mode_lower.upper()}")
        typer.echo(f"   Reasoning: {decision.reasoning}")
        typer.echo(f"   Scores: dfs={decision.scores['dfs']:.1f}  "
                   f"beam={decision.scores['beam']:.1f}  "
                   f"hybrid={decision.scores['hybrid']:.1f}\n")

    if mode_lower == "dfs":
        _prove_dfs(header, model, imports, timeout)
    elif mode_lower == "beam":
        _prove_beam(header, model, imports, samples, rounds, timeout, lean_cfg)
    elif mode_lower == "hybrid":
        _prove_hybrid(header, timeout)
    else:
        typer.echo(f"❌ Unknown mode: {mode_lower}")
        raise typer.Exit(1)


# ── Prove helpers ───────────────────────────────────────────────


def _prove_dfs(header: str, model: str, imports: str, timeout: int) -> None:
    """Run DFS (Dialogue) mode."""
    from omega.loop.inner import inner_loop, InnerLoopConfig
    full = f"{imports}\n\n{header}" if imports else header
    typer.echo(f"🔬 DFS proving: {header[:70]}...")
    cfg = InnerLoopConfig(max_rounds=50, compile_timeout=timeout,
                           budget_model_id=model, proof_sketch=True)
    r = inner_loop(full, config=cfg)
    if r.success:
        typer.echo(f"✅ Proved in {r.rounds}r ${r.budget_used_cost:.4f}")
        if r.code:
            typer.echo(f"─" * 40 + f"\n{r.code[:500]}\n" + f"─" * 40)
    else:
        typer.echo(f"❌ Failed: {r.termination} ({r.rounds}r)")
        if r.error:
            typer.echo(f"   {r.error[:300]}")


def _prove_beam(header: str, model: str, imports: str,
                samples: int, rounds: int, timeout: int, lean_cfg) -> None:
    """Run Beam (Sampling) mode."""
    from omega.llm import resolve_generate_fn
    from omega.prover.cache import ProofCache
    from omega.prover.go_prover import GoedelProver
    from omega.verify.t2_real import make_real_compile_callback
    cf = make_real_compile_callback(project_dir=lean_cfg.project_path, timeout=timeout)
    gf = resolve_generate_fn(model_id=model, temperature=0.3, max_tokens=4096)
    full = f"{imports}\n\n{header}" if imports else header
    typer.echo(f"🔬 Beam proving: {header[:70]}... (samples={samples}, corr={rounds})")
    r = GoedelProver(compile_fn=cf, generate_fn=gf,
                      num_samples=samples, max_correction_rounds=rounds,
                      cache=ProofCache()).run(full)
    if r.succeeded:
        ts = r.timings.get('total_s', 0)
        typer.echo(f"✅ Proved ({ts:.1f}s, {r.n_attempts} attempts)")
        if r.proof:
            lines = [l for l in r.proof.split("\n") if not l.startswith(("import ", "open "))]
            typer.echo(f"─" * 40 + f"\n{''.join(lines)[:500]}\n" + f"─" * 40)
    else:
        ts = r.timings.get('total_s', 0)
        typer.echo(f"❌ Failed ({ts:.1f}s)")
        if r.attempts and r.attempts[-1].get("errors"):
            for e in r.attempts[-1]["errors"][:3]:
                typer.echo(f"   {e[:200]}")


def _prove_hybrid(header: str, timeout: int) -> None:
    """Run Hybrid mode (DFS → Beam on stuck)."""
    from omega.engine.hybrid import run_hybrid_v2, HybridV2Config
    typer.echo(f"🔬 Hybrid proving: {header[:70]}...")
    cfg = HybridV2Config(budget_time_s=timeout)
    r = run_hybrid_v2(header, cfg)
    typer.echo(f"   {r.summary}")
    if r.success and r.proof:
        typer.echo(f"─" * 40 + f"\n{r.proof[:500]}\n" + f"─" * 40)
    elif r.error:
        typer.echo(f"   {r.error[:300]}")


# ── omega route ─────────────────────────────────────────────────


@app.command("route")
def route_cmd(
    theorem_header: str = typer.Argument(
        ..., help="Lean 4 theorem header to preview routing for"
    ),
) -> None:
    """Preview ModeRouter decision for a theorem."""
    from omega.engine.router import (
        DifficultyLevel, ModeRouter, ResourceProfile,
        RoutingContext, estimate_difficulty, detect_domain,
    )
    h = theorem_header.strip()
    diff = estimate_difficulty(h)
    dom = detect_domain(h) or "(unknown)"

    typer.echo(f"═══ Route Preview ═══")
    typer.echo(f"  Theorem:    {h[:70]}...")
    typer.echo(f"  Difficulty: {diff.value}")
    typer.echo(f"  Domain:     {dom}")
    router = ModeRouter()
    for lbl, rp in [("API", ResourceProfile.API_ONLY),
                    ("Local GPU", ResourceProfile.LOCAL_GPU)]:
        d = router.route(RoutingContext(theorem_header=h, resource_profile=rp))
        typer.echo(f"  [{lbl:10s}] → {d.strategy_name.upper():8s}  "
                   f"scores: dfs={d.scores['dfs']:.1f} "
                   f"beam={d.scores['beam']:.1f} "
                   f"hybrid={d.scores['hybrid']:.1f}")
    for nf in [1, 2, 3]:
        ctx = RoutingContext(
            theorem_header=h, resource_profile=ResourceProfile.API_ONLY,
            previous_failures=nf,
            history_hint="stuck" if nf >= 2 else None,
        )
        d = router.route(ctx)
        typer.echo(f"  [{nf} fail(s)] → {d.strategy_name.upper():8s}  {d.reasoning[:90]}")
    typer.echo(f"═══")


# ── omega status ────────────────────────────────────────────────


@app.command("status")
def status_cmd() -> None:
    """Show system status: models, routers, toolchain."""
    from omega.resource.model_router import ModelRouter
    typer.echo(f"═══ Ω-Architect Status ═══")
    typer.echo(ModelRouter().health_report())

    stats = ModelRouter().stats()
    if stats:
        typer.echo("\n  Routing History:")
        for mid, tiers in stats.items():
            for t, s in tiers.items():
                typer.echo(f"    {mid:35s} {t:10s} {s.total:4d} calls  "
                           f"{s.success_rate*100:5.1f}%  {s.avg_elapsed_s:6.1f}s avg")

    from omega.resource.benchmark import load_benchmark
    b = load_benchmark(refresh=False)
    typer.echo(f"\n  Hardware bench: {b.measured_at}" if b and b.measured_at
               else "\n  Hardware bench: not run (try `omega benchmark hardware`)")

    from omega.resource.lean_config import load_lean_config
    lc = load_lean_config()
    typer.echo(f"  Lean: {'✅' if lc.binaries_ok() else '❌'} {lc.version} ({lc.project_path})")
    typer.echo(f"═══")


# ── omega bench ─────────────────────────────────────────────────


@app.command("bench")
def bench_cmd(
    dataset: str = typer.Argument(
        ..., help="'minif2f' or path to .jsonl file"
    ),
    mode: str = typer.Option(
        "auto", "--mode", "-M", help="Strategy mode for proving",
    ),
    model: str = typer.Option(
        "deepseek/deepseek-v4-flash", "--model", "-m",
    ),
    max_theorems: int = typer.Option(
        10, "--max", "-n", help="Max theorems to prove (0=all)",
    ),
    output: str = typer.Option(
        "", "--output", "-o", help="Save results to JSON file",
    ),
    timeout: int = typer.Option(120, "--timeout", "-t"),
) -> None:
    """Run a benchmark on a dataset.
    
    Example::
        omega bench minif2f --mode dfs --max 5
        omega bench /path/to/problems.jsonl --mode hybrid -n 20
    """
    import json, time
    p = Path(dataset)
    if dataset == "minif2f":
        cands = [
            Path.home() / "Gitlab" / "Agentic4Sci" / "omega-architect" /
            "benchmarks" / "minif2f" / d / "valid.jsonl"
            for d in ("data", ".")
        ]
        p = next((c for c in cands if c.exists()), None)
    if not p or not p.exists():
        typer.echo(f"❌ Dataset not found: {dataset}")
        raise typer.Exit(1)
    lines = [l for l in p.read_text().splitlines() if l.strip()]
    data = [json.loads(l) for l in lines]
    thms = data[:max_theorems] if max_theorems else data
    n = len(thms)
    typer.echo(f"📚 {n} theorems | mode={mode} | model={model}\n")

    results = []
    t0 = time.perf_counter()
    for i, thm in enumerate(thms):
        header = thm.get("formal_statement", thm.get("header", ""))
        name = thm.get("name", thm.get("problem", f"p{i}"))
        typer.echo(f"[{i+1}/{n}] {name}: ", nl=False)
        tt = time.perf_counter()
        try:
            from omega.loop.inner import inner_loop, InnerLoopConfig
            cfg = InnerLoopConfig(max_rounds=30, compile_timeout=timeout,
                                   budget_model_id=model, proof_sketch=True)
            r = inner_loop(header, theorem_name=name, config=cfg)
            icon = "✅" if r.success else "❌"
            info = f"{r.rounds}r ${r.budget_used_cost:.4f} {r.termination}"
            results.append({
                "name": name, "success": r.success,
                "rounds": r.rounds, "cost": r.budget_used_cost,
                "termination": r.termination,
                "elapsed_s": round(time.perf_counter() - tt, 2),
            })
        except Exception as e:
            icon = "⚠️"
            info = str(e)[:80]
            results.append({
                "name": name, "success": False, "error": str(e)[:200],
                "elapsed_s": round(time.perf_counter() - tt, 2),
            })
        typer.echo(f"{icon} {info}  ({time.perf_counter()-tt:.1f}s)")

    ns = sum(1 for r in results if r.get("success"))
    tot = time.perf_counter() - t0
    typer.echo(f"\n═══ {ns}/{n} passed ({tot:.1f}s) ═══")
    if output:
        Path(output).write_text(json.dumps({"results": results}, indent=2))
        typer.echo(f"📄 Saved to {output}")

app.add_typer(_benchmark_app)


# ── prove-batch: Plan Layer + ProofAllocator + Inner Loop ──────


@app.command("prove-batch")
def prove_batch_cmd(
    theorems_file: str = typer.Argument(
        "",
        help="Path to JSONL file with theorems (MiniF2F format: {name, formal_statement}). "
             "Omit to read from stdin (one theorem per line).",
    ),
    budget_tier: str = typer.Option(
        "development",
        "--budget-tier",
        "-b",
        help="Budget tier: development / production / exhaustive",
    ),
    gpu_mode: str = typer.Option(
        "cpu-only",
        "--gpu-mode",
        "-g",
        help="GPU mode: cpu-only / gpu-minimal / gpu-batch",
    ),
    plan_only: bool = typer.Option(
        False,
        "--plan-only",
        "-p",
        help="Show allocation plan and exit (don't run proofs)",
    ),
    limit: int = typer.Option(
        0,
        "--limit",
        "-l",
        help="Max theorems to process (0 = all)",
    ),
    output: str = typer.Option(
        "",
        "--output",
        "-o",
        help="Save JSON results report to file",
    ),
) -> None:
    """运筹优化批量定理证明：分配→证明→汇总。

    三步流程：

    1. **计划** — PlanManager 声明预算/GPU 意图
    2. **分配** — ProofAllocator 贪心分配 N 定理到最优模型
    3. **执行** — inner_loop 逐定理使用 DeepSeek tool_calls + MCP 编译

    示例::

        # 查看分配方案（不执行）
        omega prove-batch theorems.jsonl --plan-only

        # 正式运行（开发预算，CPU 模式）
        omega prove-batch theorems.jsonl --budget-tier development

        # 生产运行
        omega prove-batch theorems.jsonl --budget-tier production --gpu-mode gpu-minimal

    JSONL 格式（每行一条）:
        {"name": "mathd_numbertheory_3", "formal_statement": "theorem ... :="}
    """
    import json
    from pathlib import Path

    from omega.plan import PlanManager

    # ── Step 0: Load theorems ───────────────────────────────────
    theorems: list[str] = []
    theorem_names: list[str] = []

    if theorems_file:
        fpath = Path(theorems_file)
        if not fpath.exists():
            typer.echo(f"❌ File not found: {theorems_file}")
            raise typer.Exit(1)
        with open(fpath) as f:
            for line in f:
                line = line.strip()
                if not line:
                    continue
                try:
                    record = json.loads(line)
                    stmt = record.get("formal_statement", "")
                    name = record.get("name", stmt[:40])
                except json.JSONDecodeError:
                    stmt = line
                    name = line[:40]
                if stmt:
                    theorems.append(stmt)
                    theorem_names.append(name)
    else:
        # Read from stdin
        import sys

        for line in sys.stdin:
            line = line.strip()
            if line:
                theorems.append(line)
                theorem_names.append(line[:40])

    if not theorems:
        typer.echo("❌ No theorems provided. Pipe them or pass a JSONL file.")
        raise typer.Exit(1)

    if limit > 0:
        theorems = theorems[:limit]
        theorem_names = theorem_names[:limit]

    typer.echo("=" * 60)
    typer.echo("Ω-Architect prove-batch")
    typer.echo("=" * 60)
    typer.echo(f"Theorems:  {len(theorems)} loaded")
    typer.echo(f"Budget:   {budget_tier}")
    typer.echo(f"GPU:      {gpu_mode}")

    # ── Step 1: Plan ────────────────────────────────────────────
    typer.echo("")
    typer.echo("─" * 60)
    typer.echo("Step 1: Plan — resolving budget/GPU/paths...")

    plan = PlanManager.resolve(budget_tier=budget_tier, gpu_mode=gpu_mode)
    try:
        pre_flight = plan.pre_flight()
        typer.echo(pre_flight)
    except Exception as e:
        typer.echo(f"⚠️  Pre-flight warning: {e}")

    # ── Step 2: Allocate ────────────────────────────────────────
    typer.echo("")
    typer.echo("─" * 60)
    typer.echo("Step 2: Allocate — multi-constraint 运筹 optimization...")

    summary = plan.allocation_summary(theorems)
    typer.echo("")
    typer.echo(summary)
    typer.echo("")

    if plan_only:
        typer.echo("✅ Plan-only mode. Exiting (use --plan-only to see allocation).")
        return

    # ── Step 3: Prove ───────────────────────────────────────────
    typer.echo("─" * 60)
    typer.echo("Step 3: Prove — inner_loop per theorem")
    typer.echo("")

    import time as _time

    from omega.loop.inner import InnerLoopConfig, inner_loop
    from omega.loop.mcp_sync import PersistentMcpClient
    from omega.resource.budget import BudgetTracker

    assignments = plan.allocate(theorems)
    results: list[dict] = []
    t_start = _time.perf_counter()

    for i, (header, assn) in enumerate(zip(theorems, assignments, strict=True)):
        name = theorem_names[i] if i < len(theorem_names) else header[:40]
        typer.echo(
            f"[{i + 1}/{len(theorems)}] {name[:50]:50s} "
            f"→ {assn.model_id.split('/')[-1]:20s} "
            f"(p={assn.estimated_success_prob:.2f})"
        )

        if budget_tier == "development" and assn.model_id != "local/default":
            typer.echo(f"       ⏭️  Development mode — skipping (would run {assn.model_id})")
            results.append({
                "name": name,
                "header": header,
                "model": assn.model_id,
                "success": False,
                "reason": "development_skip",
                "error": None,
                "elapsed_s": 0.0,
            })
            continue

        # Create per-theorem budget tracker & MCP client
        bt = BudgetTracker()
        mcp = PersistentMcpClient()
        try:
            mcp.initialize()
        except Exception as e:
            typer.echo(f"       ❌ MCP init failed: {e}")
            results.append({
                "name": name,
                "header": header,
                "model": assn.model_id,
                "success": False,
                "reason": "mcp_error",
                "error": str(e),
                "elapsed_s": 0.0,
            })
            continue

        cfg = InnerLoopConfig(
            model=assn.model_id,
            budget_model_id=assn.model_id,
            max_rounds=10,
        )

        t0 = _time.perf_counter()
        try:
            result = inner_loop(
                theorem_header=header,
                theorem_name=name,
                config=cfg,
                budget=bt,
                mcp=mcp,
                plan=plan.execution,
            )
            elapsed = _time.perf_counter() - t0

            results.append({
                "name": name,
                "header": header,
                "model": assn.model_id,
                "success": result.success,
                "reason": result.termination,
                "error": result.error,
                "rounds": result.rounds,
                "elapsed_s": round(elapsed, 2),
                "cost": result.budget_used_cost,
                "tokens": result.budget_used_tokens,
            })

            icon = "✅" if result.success else "❌"
            typer.echo(
                f"       {icon} {result.termination} "
                f"({result.rounds}r, ${result.budget_used_cost:.4f}, {elapsed:.1f}s)"
            )
        except Exception as e:
            elapsed = _time.perf_counter() - t0
            typer.echo(f"       ❌ Exception: {e}")
            results.append({
                "name": name,
                "header": header,
                "model": assn.model_id,
                "success": False,
                "reason": "exception",
                "error": str(e),
                "elapsed_s": round(elapsed, 2),
            })
        finally:
            try:
                mcp.close()
            except Exception:
                pass

    # ── Summary ─────────────────────────────────────────────────
    total_elapsed = _time.perf_counter() - t_start
    n_success = sum(1 for r in results if r.get("success"))
    n_fail = sum(1 for r in results if not r.get("success"))
    total_cost = sum(r.get("cost", 0.0) for r in results)

    typer.echo("")
    typer.echo("=" * 60)
    typer.echo("Batch Result Summary")
    typer.echo("=" * 60)
    typer.echo(f"  ✅ {n_success} succeeded")
    typer.echo(f"  ❌ {n_fail} failed")
    typer.echo(f"  ⏱  {total_elapsed:.1f}s total")
    typer.echo(f"  💰 ${total_cost:.4f} total cost")
    typer.echo("")

    # Save results
    if output:
        out_path = Path(output)
        out_path.parent.mkdir(parents=True, exist_ok=True)
        out_path.write_text(json.dumps({
            "budget_tier": budget_tier,
            "gpu_mode": gpu_mode,
            "n_theorems": len(theorems),
            "n_succeeded": n_success,
            "n_failed": n_fail,
            "total_elapsed_s": round(total_elapsed, 2),
            "total_cost": round(total_cost, 4),
            "results": results,
        }, indent=2, ensure_ascii=False))
        typer.echo(f"📄 Report saved to {out_path}")


# ── main entry point ────────────────────────────────────────────
