#!/usr/bin/env python3
"""Omega CLI — ``omega init``, ``omega config``, and ``omega prove``.

Entry point::

    def main():
        typer_app()
"""

from __future__ import annotations

import json
import sys
from pathlib import Path
from typing import Any

import typer

from omega.resource.config import (
    BudgetConfig,
    _find_config_file,
    load_config,
    reset_config_cache,
)

app = typer.Typer(
    name="omega",
    help="Ω-Architect — Open Formal Theorem Proving for Physics & Quantum",
    add_completion=False,
)

# ── Template content ────────────────────────────────────────────


def _default_template() -> str:
    """Generate a commented omega.toml template."""
    return """# =============================================================================
# Omega Budget Configuration (auto-generated by ``omega init``)
# =============================================================================
# Edit this file to control resource allocation per theorem.
#
# Loading order (later overrides earlier):
#   1. Code defaults (BudgetConfig class)
#   2. This file
#   3. OMEGA_* environment variables
#   4. --budget-* CLI flags
# =============================================================================

# ── Budget Dimensions ──────────────────────────────────────────
[budget]
# Maximum tokens across all models (1M ≈ ~$0.57 DeepSeek, ~$18 Claude Sonnet)
max_tokens = 1_000_000

# Maximum USD cost (paid providers only; free models skip cost tracking)
max_cost_usd = 0.50

# Maximum wall-clock seconds per theorem
max_time_s = 300.0

# Maximum T2 compile attempts
max_attempts = 50

# Minimum proposer confidence (0.0 = accept all, 1.0 = only high-confidence)
min_confidence = 0.3

# ── Epoch (Self-Correction Round) Tracking ─────────────────────
[budget.epochs]
# Maximum correction rounds (initial sampling counts as epoch 1)
max_epochs = 5

# Convergence threshold: if average error-reduction rate < this over window,
# we declare "converged" and stop (avoids endless corrections)
convergence_threshold = 0.1

# Sliding window for convergence detection (must be >= 2)
window = 3

# ── Research Phase Budget ──────────────────────────────────────
[research]
# Tokens reserved for knowledge research (arXiv papers, GitHub code analysis)
max_tokens = 50_000

# Seconds reserved for research phase
max_time_s = 60.0

# Maximum related papers to retrieve
max_papers = 5

# Maximum GitHub Lean4 code results to retrieve
max_github_results = 10

# ── Model Pricing ──────────────────────────────────────────────
[models]
# Free-model prefixes — these skip cost tracking
free = ["ollama/", "local/"]

# Paid model prices (USD per token).
# Add your own models here; unknown models are treated as free.
"""
    for model_id, prices in dict(BudgetConfig().model_prices).items():
        in_rate = prices.get("input_per_token", 0)
        out_rate = prices.get("output_per_token", 0)
        lines = []
        lines.append(f'[models."{model_id}"]')
        lines.append(f"input_per_token = {in_rate!r}    # ${in_rate * 1e6:.2f}/M tokens")
        lines.append(f"output_per_token = {out_rate!r}   # ${out_rate * 1e6:.2f}/M tokens")
        lines.append("")
        section = "\n".join(lines)
        # indent
        section = "\n".join(section.split("\n"))

    return _default_template.__doc__  # type: ignore[return-value]


def _config_template(cfg: BudgetConfig | None = None) -> str:
    """Return a commented TOML template string."""
    if cfg is None:
        cfg = BudgetConfig()
    buf: list[str] = []

    buf.append("# Ω-Architect Budget Configuration")
    buf.append("# Uncomment and edit values to override defaults.")
    buf.append("")

    # ── Budget ──
    buf.append("[budget]")
    buf.append(f"# max_tokens = {cfg.max_tokens}    # 1M = ~$0.57 DeepSeek, ~$18 Claude")
    buf.append(f"# max_cost_usd = {cfg.max_cost_usd}")
    buf.append(f"# max_time_s = {cfg.max_time_s}")
    buf.append(f"# max_attempts = {cfg.max_attempts}")
    buf.append(f"# min_confidence = {cfg.min_confidence}")
    buf.append("")
    buf.append("[budget.epochs]")
    buf.append(f"# max_epochs = {cfg.epochs.max_epochs}")
    buf.append(f"# convergence_threshold = {cfg.epochs.convergence_threshold}")
    buf.append(f"# window = {cfg.epochs.window}")
    buf.append("")

    # ── Research ──
    buf.append("[research]")
    buf.append(f"# max_tokens = {cfg.research_max_tokens}")
    buf.append(f"# max_time_s = {cfg.research_max_time_s}")
    buf.append(f"# max_papers = {cfg.max_papers}")
    buf.append(f"# max_github_results = {cfg.max_github_results}")
    buf.append("")

    # ── Models ──
    buf.append("[models]")
    buf.append(f"free = {json.dumps(cfg.free_models)}")
    buf.append("")
    for model_id, prices in cfg.model_prices.items():
        in_rate = prices.get("input_per_token", 0)
        out_rate = prices.get("output_per_token", 0)
        buf.append(f'[models."{model_id}"]')
        buf.append(f"# input_per_token = {in_rate!r}    # ${in_rate * 1e6:.2f}/M")
        buf.append(f"# output_per_token = {out_rate!r}   # ${out_rate * 1e6:.2f}/M")
        buf.append("")

    return "\n".join(buf)


# ── CLI Commands ────────────────────────────────────────────────


@app.callback()
def main_callback(
    ctx: typer.Context,
    config: str = typer.Option(
        "",
        "--config",
        "-c",
        help="Path to omega.toml config file",
        envvar="OMEGA_CONFIG",
    ),
) -> None:
    """Ω-Architect CLI — resource configuration and theorem proving."""
    ctx.ensure_object(dict)
    ctx.obj["config_path"] = config


@app.command("init")
def init_cmd(
    force: bool = typer.Option(False, "--force", "-f", help="Overwrite existing file"),
    output: str = typer.Option(
        "omega.toml",
        "--output",
        "-o",
        help="Output path for the config template",
    ),
) -> None:
    """Generate a commented omega.toml configuration template."""
    out_path = Path(output)
    if out_path.exists() and not force:
        typer.echo(f"❌ {out_path} already exists. Use --force to overwrite.")
        raise typer.Exit(1)

    template = _config_template()
    out_path.write_text(template, encoding="utf-8")
    typer.echo(f"✅ Generated {out_path}")
    typer.echo("")
    typer.echo("Edit the file to set your budget limits, then run:")
    typer.echo("  omega config show    # verify loaded config")
    typer.echo("  omega prove ...      # run with custom budget")


@app.command("config")
def config_cmd(
    ctx: typer.Context,
    action: str = typer.Argument(
        "show",
        help="Action: show / set / path",
    ),
    key: str = typer.Option("", "--key", "-k", help="Dot-path key (e.g., budget.max_tokens)"),
    value: str = typer.Option("", "--value", "-v", help="Value to set"),
) -> None:
    """View or modify Omega configuration.

    Actions:

    **show** (default) — Display current config with source annotation.

    **set** — Save a key=value to the config file (requires --key and --value).

    **path** — Show config file discovery path.
    """
    cfg_path = ctx.obj.get("config_path", "")

    if action == "path":
        found = _find_config_file()
        if found:
            typer.echo(f"📄 Config file: {found}")
        else:
            typer.echo("📄 No config file found (using defaults)")
        typer.echo(f"   OMEGA_CONFIG env: {cfg_path or '(not set)'}")
        typer.echo(f"   CWD:              {Path.cwd()}")
        return

    if action == "set":
        if not key:
            typer.echo("❌ --key is required for 'set' action")
            raise typer.Exit(1)
        if not value:
            typer.echo("❌ --value is required for 'set' action")
            raise typer.Exit(1)

        # Find or create config file
        config_file = cfg_path or _find_config_file() or "omega.toml"
        cfg_path_obj = Path(config_file)

        if cfg_path_obj.is_file():
            current = cfg_path_obj.read_text(encoding="utf-8")
        else:
            current = _config_template()
            cfg_path_obj.parent.mkdir(parents=True, exist_ok=True)

        # Parse key into TOML section path
        parts = key.split(".")
        if len(parts) >= 2:
            section = ".".join(parts[:-1])
            k = parts[-1]
            # Try to find and uncomment the line
            import re

            # Match commented or uncommented key
            pattern = re.compile(r"^(#\s*)?(" + re.escape(k) + r")\s*=\s*.*$", re.MULTILINE)
            # Parse value as number if possible
            try:
                parsed_val = json.loads(value)
            except (json.JSONDecodeError, ValueError):
                parsed_val = value

            # Format value
            if isinstance(parsed_val, bool):
                val_str = "true" if parsed_val else "false"
            elif isinstance(parsed_val, (int, float)):
                val_str = str(parsed_val)
            elif isinstance(parsed_val, list):
                val_str = json.dumps(parsed_val)
            else:
                val_str = f'"{parsed_val}"'

            replacement = f"{k} = {val_str}"
            if pattern.search(current):
                updated = pattern.sub(replacement, current)
            else:
                # Append to the right section
                section_header = f"[{section}]"
                if section_header in current:
                    # Find section and add after it
                    updated = current.replace(section_header, f"{section_header}\n{replacement}")
                else:
                    updated = current + f"\n[{section}]\n{replacement}\n"

            cfg_path_obj.write_text(updated, encoding="utf-8")
            reset_config_cache()
            typer.echo(f"✅ Set {key} = {val_str} in {cfg_path_obj}")
        else:
            typer.echo(
                "❌ Key must have at least two dot-separated parts (e.g., budget.max_tokens)"
            )
            raise typer.Exit(1)
        return

    # Default: show
    reset_config_cache()
    cfg = load_config(config_path=cfg_path)

    typer.echo("=" * 60)
    typer.echo("Ω-Architect Configuration")
    typer.echo("=" * 60)
    if cfg._source_file:
        typer.echo(f"📄 Source: {cfg._source_file}")
    else:
        typer.echo("📄 Source: defaults (no config file)")
    typer.echo("")

    # Display as formatted key=value
    flat = _flatten_config(cfg)
    for key_path, val in sorted(flat.items()):
        typer.echo(f"  {key_path:45s} = {val!r}")

    typer.echo("")
    typer.echo("To change: edit omega.toml or use `omega config set --key ... --value ...`")


# ── Helpers ─────────────────────────────────────────────────────


def _flatten_config(cfg: BudgetConfig) -> dict[str, Any]:
    """Flatten a BudgetConfig into dot-path key=value pairs."""
    result: dict[str, Any] = {}

    # Budget dimensions
    b = {
        "budget.max_tokens": cfg.max_tokens,
        "budget.max_cost_usd": cfg.max_cost_usd,
        "budget.max_time_s": cfg.max_time_s,
        "budget.max_attempts": cfg.max_attempts,
        "budget.min_confidence": cfg.min_confidence,
        "budget.epochs.max_epochs": cfg.epochs.max_epochs,
        "budget.epochs.convergence_threshold": cfg.epochs.convergence_threshold,
        "budget.epochs.window": cfg.epochs.window,
    }

    # Research
    r = {
        "research.max_tokens": cfg.research_max_tokens,
        "research.max_time_s": cfg.research_max_time_s,
        "research.max_papers": cfg.max_papers,
        "research.max_github_results": cfg.max_github_results,
    }

    # Models
    m: dict[str, Any] = {"models.free": list(cfg.free_models)}
    for model_id, prices in cfg.model_prices.items():
        short = model_id.replace("/", ".")
        m[f"models.{short}.input_per_token"] = prices.get("input_per_token", 0)
        m[f"models.{short}.output_per_token"] = prices.get("output_per_token", 0)

    result.update(b)
    result.update(r)
    result.update(m)
    return result


# ── Entry point ─────────────────────────────────────────────────


def main() -> None:
    app()


if __name__ == "__main__":
    main()


# ── Run command ────────────────────────────────────────────────


@app.command("run")
def run_cmd(
    research_goal: str = typer.Argument(
        ..., help="Research goal description, e.g. 'Formalize NV spin Hamiltonian'"
    ),
    time_hours: float = typer.Option(
        2.0, "--time", "-t", help="Max run time in hours (2, 4, 8, 12, etc.)"
    ),
    model: str = typer.Option("local/default", "--model", "-m", help="LLM model ID to use"),
    checkpoint: str = typer.Option(
        "", "--resume", "-r", help="Path to checkpoint file to resume from"
    ),
) -> None:
    """Run autonomous proof search for a research goal.

    Runs unattended for *--time* hours, proving theorems related to the
    research goal. Checkpoints are saved periodically — use ``--resume``
    to continue from a previous run.

    Example:
        omega run "Formalize NV center spin Hamiltonian" --time 4
        omega run "Prove Maxwell equations in Lean" --time 8 --model deepseek/deepseek-chat
        omega run "Continue previous session" --resume ~/.omega/checkpoints/checkpoint_20260606_120000.json
    """
    from omega.runner import OmegaRunner, TheoremSpec

    # Build theorem list from the research goal keywords
    # For now, we create a default theorem based on the goal name
    theorems = [
        TheoremSpec(
            header=f"theorem research_goal_{i} : True :=",
            description=research_goal,
            priority=1,
            domain="general",
        )
        for i in range(1)
    ]

    time_budget_s = time_hours * 3600.0
    typer.echo(f"🚀 Starting {time_hours}h autonomous proof search")
    typer.echo(f"   Goal: {research_goal}")
    typer.echo(f"   Model: {model}")
    typer.echo(f"   Budget: {time_budget_s:.0f}s wall clock")
    typer.echo("")

    runner = OmegaRunner(
        time_budget_s=time_budget_s,
        model_id=model,
    )

    report = runner.run(
        research_goal=research_goal,
        theorems=theorems,
        resume_checkpoint=checkpoint,
    )

    typer.echo(report.summary())
    typer.echo("")

    # Show allocator provenance
    provenance = runner._allocator.provenance_summary()
    typer.echo(provenance)

    # Show cost report
    cost = runner._allocator.cost_report()
    typer.echo("\n💰 Cost breakdown:")
    typer.echo(
        f"   Pro (blueprint):  ${cost['pro_spent']:.4f} / ${cost['pro_remaining'] + cost['pro_spent']:.2f} budget"
    )
    typer.echo(
        f"   Flash (append):   ${cost['flash_spent']:.4f} / ${cost['flash_remaining'] + cost['flash_spent']:.2f} budget"
    )
    typer.echo(f"   Total:            ${cost['total_usd']:.4f}")

    # Show dynamic tok/s if local model was used
    tok_s = runner._bt.dynamic_tok_s()
    if tok_s > 0:
        typer.echo(f"⚡ Dynamic tok/s: {tok_s:.1f}")


@app.command("benchmark")
def benchmark_cmd(
    refresh: bool = typer.Option(False, "--refresh", "-r", help="Re-run benchmarks"),
) -> None:
    """Benchmark local ollama models and show token throughput."""
    from omega.resource.benchmark import discover_and_benchmark, load_benchmark

    typer.echo("=" * 60)
    typer.echo("Ω-Architect Hardware Benchmark")
    typer.echo("=" * 60)

    if refresh:
        data = discover_and_benchmark()
        data.save()
    else:
        data = load_benchmark(refresh=False)

    typer.echo(f"Measured at: {data.measured_at}")
    typer.echo(f"Hardware:    {data.hardware}")
    typer.echo("")
    typer.echo(f"{'Model':30s} {'tok/s':>8} {'tok/call':>10} {'12h tokens':>14}")
    typer.echo("-" * 62)
    for name, r in data.models.items():
        tok_s = r.avg_tok_s
        tok_call = r.avg_tokens_per_call
        est_12h = int(tok_s * 43200)
        typer.echo(f"{name:30s} {tok_s:>8.1f} {tok_call:>10} {est_12h:>14,}")

    typer.echo("")
    typer.echo('Tip: run `omega run "goal" --time 4` to use these rates automatically.')
